travis:
  secure:
    BINSTAR_TOKEN: ZvXgFAUEEz0HxkOhO8nJTW3EAtIWcVNdQ29Fn11I9xJQ1pHESL4bRRI8Xd4l9gTa6vEJ6pa7bN1VbhBAEuUGTAY13ny4gsdJirbsMkVS1szpjxFOm0uaNrzj7dQCnsG3phb8k4wuLTD+gIP7AzyHi2qLLFBciF9H0oyUqjUZJKYQDyFstkstHvwNvx5hmXN/0aUJQzVMb014cYn4xeWwnvQgmVW8yFcvClZnPJlE58r+OBfXITbK4sVREP54kAhovSJjyPPzx21qX9dLUXS+Ldi7LrnB4vBhfe66lMIAGSg6LEIajNXLy7Yb8E/H4cguSGLJy6GoG/ZZ9lw+6svr3fSC2qvXwjBuxLdNLt8BZNpogLs8wn/90XxkAdikMWU1eFZoO0G4pcJ2HbYHrs/qLiFVi/UdPCsVLQ+bjBVU2MGXzRWN6XETsv6Xx5T88k1GUPSr2jqQlsVi/C3nmKCLj3/A3B+r/HRpkqgqwoRvCptTWnA+mPlcpfmw79Kzf8ao4jf0eIkBGTQyGOO4EHU8XjeqO3X1RJOxl2XYlzrBQcpjSpKjGTXPE4/LQLJGW3eupwd/Ex9K30G2DhNMWSOlZ5xp1TzyVJp/0CY2UfLaMfDH46OxN7p36NgIfbJGz/6mjlixrvYU335VShBfJF8eRGaKZH4vemvaPuTwmkMUiV4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
