travis:
  secure:
    BINSTAR_TOKEN: rlklxHoo1B55WI8UmmhapjlWPOL9b9ud6jTN+GQi8MJPouCSnedDHVU7MCc8iuAvax4t/auBDY41dXJKHbLZsKWnyOQSPXeeDncKgwGzDcW04V3H82+fQBHHuD+s1vCK+XKNs6ppjUtGlzcjnpMQRbsBk1H3KBuV+YeXTiPhAen3+I3FSTLzozbHPXqgo8LjW/D0ntv9PHafwA/LdbVsbuyrAMKPehwXjVuZDK7AYFCF31T6o694sbmJL9zpzgwRUiNG2LBQCThhykBckZO8tY2fK/wVFgPo2+DiWHXL/zQeZu0vRB9FR7bsBzqUd6loVDmaeqXUd/RsWD0qloJ/0kgRkhkp+7y2OG05paJnl6hKTm8pVoqwRGe20D/jYrfOz9de9474sBSE/uAON9/cjWTbnWZV8Fu5A7sK0PYHaVLAqZ1CAi7wMtrGnYcx+S2qlJuCFtWC/lU06jdAllXfpaaeK+aKK0BLEgHtL6zJNyFkeUK57oXHqgUixUXTsOCkaNU5hazmprIh3x6EnIo+7wtONeF0iR5cS1UqmuEmFn+ajIm4rd0lZvTj96WU5J91tgLuB4KxX6GHNbpOxO1DXesgip9LZxkcHVNxsCnv7lvIKcbYv6+WgUmpsPx35U7rWyYkCivwJYMKnDHpe0aTycdeuUeRWxJ9iaRBjgjXUV0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
